### ISSUE TITLE
Need info

### ISSUE THREAD

**Issue by utkarshs07** [Anakros/webrtc-ios-dynamic#1]
This framework contains native code of WebRTC like static library or only objC code (.h & .m) placed at webrtc/sdk/objc ???

Build configuration: release or debug?

**Comment by AlexKMDev** [comment]
This dynamic framework contains only objc wrapper and it's updated from `webrtc/sdk/objc/Framework`. `talk/app/webrtc/objc/public` (from which other frameworks was built, like `libjingle_peerconnection`) is outdated and will be removed in the future.

Build configuration: Release, I assume. You can build it yourself and you will see framework itself and debugging symbols `.dsym` file, which is needed for debugging.

**Comment by utkarshs07** [comment]
actually i don't know the process of building this framework .. can you guide me?

and if this framework only contains objC wrapper then what about the webrtc code... do we need to build separate file for this and using two files one is wrapper second is webrtc?

**Comment by x3mall1986** [comment]
Videocall work fine only with this framework with h264 codex

**Comment by AlexKMDev** [comment]
@utkarshs07 no, it will work out of the box. It contains webrtc code, but only objc wrapper headers are exposed.

Build instructions there: https://webrtc.org/native-code/ios/ You just need to run `webrtc/build/ios/build_ios_libs.sh` after cloning repository. Also, I uploaded `.dSYM` in the releases. https://github.com/Anakros/WebRTC-iOS/releases

**Comment by utkarshs07** [comment]
Actually i need static library and headers. I don't want framework. 

In .sh file, i've made few changes:

from:

```
BUILD_TYPE="framework"
PERFORM_CLEAN=0
FLAVOR="Profile"
POINT_VERSION="0"
```

to:

```
BUILD_TYPE="static_only"
PERFORM_CLEAN=0
FLAVOR="Release"
POINT_VERSION="0"
```

when i run giving me error of **ninja: command not found**

```
$ /Users/vikrantjain/LocalGit/webrtc-build-scripts-master/ios/webrtc/src/webrtc/build/ios/build_ios_libs.sh 

Building WebRTC arch: arm
Building static only.
~/LocalGit/webrtc-build-scripts-master/ios/webrtc/src ~
Updating projects from gyp files...
~
/Users/vikrantjain/LocalGit/webrtc-build-scripts-master/ios/webrtc/src/webrtc/build/ios/build_ios_libs.sh: line 98: ninja: command not found
```

Though i've already build static library of **r13570**.
if i copy headers from **sdk** folder instead of using **talk**
and in each header file if i modify #import statement 

from:
`#import <WebRTC/RTCMediaStreamTrack.h>`
to:
`#import "RTCMediaStreamTrack.h"`

will it work?

**Comment by AlexKMDev** [comment]
I don't know, you can ask there https://groups.google.com/forum/#!forum/discuss-webrtc

**Comment by x3mall1986** [comment]
You should add **depot_tools** to your **PATH** and **ninja** command will be work:
$ export PATH=`pwd`/depot_tools:"$PATH"

**Comment by utkarshs07** [comment]
Well thank you guys for the info. After spending hours I've successfully built static library.
