### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by gunjot-mansa** [Anakros/webrtc-ios-dynamic#11]
Hi

Apple has made it mandatory for all apps to support ipv6 - 

> At WWDC 2015 we announced the transition to IPv6-only network services in iOS 9. Starting June 1, 2016 all apps submitted to the App Store must support IPv6-only networking. 

[Apple Reference](https://developer.apple.com/news/?id=05042016a)

Apple has provided a way to test IPv6 DNS64/NAT64 compatibility—which is the type of network most cellular carriers are deploying—is to set up a local IPv6 DNS64/NAT64 network with your Mac. [Test for IPv6 DNS64/NAT64 Compatibility Regularly](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16)

I am not able to make it work with ipv6. It works perfectly fine with ipv4, but as soon i switch my network to ipv6 - it just shows black screen in place of remote video.

I am using latest pre-release r14604. I have also tried **latest stable release** i.e r13869: M54, Update 6, still no luck!

I have also found other thread #7 , confirming its working on ipv6, but it is not(atleast for my case).

Can you please confirm?

**Comment by NiKrause** [comment]
what about the stable release? The prerelease had another issue to me. (wrong orientation of camera as soon as remote stream is added)

**Comment by gunjot-mansa** [comment]
Hi Nico,

Very thanks for your reply!!

Yes, i have tried on latest stable release as well - i.e r13869: M54, Update  6

In fact, i have been testing this on repository [AppRTC-iOS](https://github.com/inspiraluna/AppRTC-iOS) provided by you. I have tried both on this:- 
1. Latest Stable Release  i.e r13869: M54, Update 6
2. Latest pre-release r14604

Both are giving me issues in case of ipv6. It works perfect with ipv4, but doesn't show remote stream, as soon i switch it to ipv6. Web Socket connection, Ice Candidate generation  and signalling works fine. It also receives a remote stream, but remote stream doesn't show up on Screen.

**Comment by pritambarhate** [comment]
Hi Gunjot Singh,

I had confirmed the IPv6 working on the Issue#7 (https://github.com/Anakros/WebRTC/issues/7) with Google's AppRTC Demo. This demo comes with official WebRTC framework source code. I have checked it a couple of times and found it working with Apple's IPv6/Nat64 network. However, this is plain WebRTC without any media server.

Since here you have mentioned that you are testing with inspiraluna's  demo which uses Kurento on the backend. I am assuming you are trying to get it to work with Kurento. For some reason I have not been able to get it work with Kurento. I have posted my question about this here: http://stackoverflow.com/questions/40078763/has-anyone-managed-to-get-group-calls-working-with-kurento-on-ios-with-ipv6-only

But no replies so far. This is very strange. But haven't found a solution thus far. 

 I found inspiraluna's demo today itself. I am planning to test it out with Kurento.

**Comment by gunjot-mansa** [comment]
Hi Pritam,

Very thanks for your reply!

Yes, you are correct. I have also replicated same ipv6 issue in web browsers using Kurento at Server end. So issue seems to be with Kurento only!
I am still looking into this issue, and will definitely share any progress!

**Comment by pritambarhate** [comment]
@inspiraluna : I tried your project https://github.com/inspiraluna/AppRTC-iOS. It seems to work well with IPv4. But when I tried it out with IPv6/Nat64 as required by Apple. it didn't work. In your logs in the ReadMe you have mentioned that you tried out IPv6. But it wasn't clear if you managed to get it to run on IPv6. Can you please confirm if the Kurento Sample worked for you on IPv6? 

Thanks,

Pritam.

**Comment by NiKrause** [comment]
Sorry, I did not try IPv6 yet. Cannot confirm. My problem was related but this now seems something different.
I need to setup an IPv6 network as it seems. I do not have a lot of experience with IPv6 yet.
But if you don’t mind we could solve / check it together.

N.

**Comment by pritambarhate** [comment]
Hi Nico,

With Mac OS X 10.11 it is very easy to set up IPv6 network for testing. The instructions from Apple are here: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16

Basically, you need a connection from LAN which you can share with the MacBook's WiFi. This WiFi network can be created with Nat64 option which creates a network similar to what Apple tests the apps in. 

> you don’t mind we could solve / check it together.

My skype id is: pritambarhate and my gmail is pritambarhate [at] gmail [dot] com

Please send me a request there, if you want to chat to check this together.

**Comment by gunjot-mansa** [comment]
Hi guys

I would love to be a part of it! 
My email - garry.sin00@gmail.com

Thanks

**Comment by gunjot-mansa** [comment]
Regarding Apple Approval process, 

As Apple need iOS apps to fully support ipv6 and not server side 

> Starting June 1, 2016 all apps submitted to the App Store must support IPv6-only networking. 

Since Issue is on server side and app is fully supporting ipv6. So Apple might cut some slack and approve it. But that is just a guess - In first shot - they will reject it right away, but after reasoning - i think they will understand.

Still need to go deep to figure out the issue. 

SRFLX candidates are still ipv4 - while connecting to Apple DNS64/NAT64 IPV6, which should be used for making a connection by kurento and app.  Still looking!!

**Comment by NiKrause** [comment]
Thanks, I was thinking the same. …

But my suggestion would have been anyways (for my code) to implement a default pure peer2peer solution  (which seems to definitely work for ipv6) and would be approved by apple)

(only the recording function needs kurento or a media server so far. - which could be called a bug if its not working)

If we want to make this running we need a fully working IPv6 environment with kurento on IPv6 only, Applikation Server and even turn/stun working on IPv6 only too!

Let me know what you think. ( I am still interested - but sharing the work a bit would help all of us I guess)

So long -

N.

**Comment by pritambarhate** [comment]
> If we want to make this running we need a fully working IPv6 environment with kurento on IPv6 only, Applikation Server and even turn/stun working on IPv6 only too!

Actually, I am trying to get it to work where Kurento server has IPv4 address while the iOS client is in IPv6 only network. (No luck so far) I am using EC2 for Kurento. It may sound unbelievable but as of now EC2 doesn't support IPv6 IP addresses for the instances. Only load balancers can have IPv6 addresses. I am not sure how it will work out if we put a load balancer in front of Kurento in tcp only mode. Anyways I want to avoid it if possible. 

> only the recording function needs kurento or a media server so far.

I have seen that if you want to go beyond 1 to 1 calls in WebRTC, you need a media server to get good call quality. 

Also, I think when I said above Nico's application uses Kurento in the backend, I was wrong. I quickly skimmed through the readme and it mentioned Kurento so I thought it used Kurento.  But it seems that the backend he is using doesn't use Kurento. @Nico: Please correct me if I am wrong.

**Comment by NiKrause** [comment]
Hi,

I am heavily using Kurento at the moment mainly for recording features on the server side. But I am thinking on providing an alternative approach to have a true peer2peer connection when I don’t need the recording. This could be easily done with IPv6. And should work already now.

So Kurento has to work with IPv6.
TURN/STUN Server also.
What is the second first I would try if I can run my tomcat or nodejs in a IPv6 only environment.

I am quite busy. But I’ll try to contact you on skype during the next days.

But I guess we are a bit offtopic here. Since Anakros/WebRTC works with IPv6 without problems as it seems in Peer2Peer mode. We could create an issue on my Git? And keep the discussion going on there.

Cheers!

Nico

**Comment by pritambarhate** [comment]
> We could create an issue on my Git? And keep the discussion going on there. 

Yes, that will work. 

> I’ll try to contact you on skype during the next days

Sure thanks.

**Comment by dharmeshrchauhan** [comment]
ipv6 network is not working for me when I tried latest build 57.5.16123. Actually I am using Kurento Toolbox for IOS app which uses WebRTC framework under the hood. We are using kurento media server in the backend.
