### ISSUE TITLE
r14604 can't run on emulators

### ISSUE THREAD

**Issue by antoniotuzzi** [Anakros/webrtc-ios-dynamic#12]
r14604 is missing symbols
(the binary is suspect: 6.6Mb)

I'm getting this missing objects:

  "_OBJC_CLASS_$_RTCConfiguration", referenced from:
  "_OBJC_CLASS_$_RTCEAGLVideoView", referenced from:
  "_OBJC_CLASS_$_RTCIceServer", referenced from:
  "_OBJC_CLASS_$_RTCMediaConstraints", referenced from:
  "_OBJC_CLASS_$_RTCPeerConnectionFactory", referenced from:
  "_OBJC_CLASS_$_RTCSessionDescription", referenced from:
  "_RTCCleanupSSL", referenced from:
  "_RTCInitializeSSL", referenced from:

**Comment by AlexKMDev** [comment]
Are you using iPhone 5 simulator? The framework doesn't contain x86 binary, so it will not work under x86 simulators (only iPhone 5 in the latest Xcode release) until webrtc developers make this possible in the build script.

**Comment by antoniotuzzi** [comment]
yes, iPhone5 5s 6 or 6s

**Comment by antoniotuzzi** [comment]
(r14270 is working)

**Comment by AlexKMDev** [comment]
It will not work under x86 (iPhone 5) simulators until WebRTC developers make this possible in the build script. Works under x64 simulators though.
