### ISSUE TITLE
No video in remote peer

### ISSUE THREAD

**Issue by richieroldan** [Anakros/webrtc-ios-dynamic#13]
First of all thanks for this great library.
I am creating a simple one to one app (iphone5 to desktop). 
SDP negotiation was successful and I can view my local stream and remote stream from the other peer in my device (iphone). but on the other peer they can't view my stream (desktop). Maybe there's a problem with in my local stream setup?
Please help.

here's my code setting up local stream

```
private func setupLocalTracks() -> RTCMediaStream{
        let stream = self._factory?.mediaStream(withStreamId: "echo")
        let audioTrack = self._factory?.audioTrack(withTrackId: "echoA")
        let videoTrack = getCameraTrack()
        stream?.addAudioTrack(audioTrack!)
        stream?.addVideoTrack(videoTrack)
      
        return stream!
    }
private func getCameraTrack() -> RTCVideoTrack{
        
        let videoSource =  _factory?.avFoundationVideoSource(with: RTCMediaConstraints(mandatoryConstraints: _mandatoryConstraints, optionalConstraints : _optionalConstraints))
        videoSource?.captureSession.startRunning() 
        flooxPeerConnectionDelegate?.onCamera(videoSource: videoSource!)
        let videoTrack = _factory?.videoTrack(with: videoSource!, trackId: "echoV")
        
        return videoTrack!
}
```

**Comment by andyryan** [comment]
Did you find a solution to this as I am having a similar issue. Audio is coming in from the desktop client (chrome) but not being sent by ios app. According to webrtc internals the bitrate for video is 0
