### ISSUE TITLE
Missing required architecture i386

### ISSUE THREAD

**Issue by mikhailovas** [Anakros/webrtc-ios-dynamic#16]
The last framework build doesn't include i386 architecture. (56.10.15101)
Please fix it.

**Comment by AlexKMDev** [comment]
That's because it has building issues in the upstream. I can't fix it until WebRTC developers fix i386 compilation issues. You can see not so detailed explanation there: https://chromium.googlesource.com/external/webrtc/+/master/webrtc/build/ios/build_ios_libs.sh#149. The only method to make it work (for now) is a compilation of a static library.

By the way, what's the point of using old simulator devices?

**Comment by jondwillis** [comment]
@Anakros I was able to get i386 to work by applying the following patch:

```diff
diff --git a/tools-webrtc/ios/build_ios_libs.sh b/tools-webrtc/ios/build_ios_libs.sh
index 285b375..9a7b977 100755
--- a/tools-webrtc/ios/build_ios_libs.sh
+++ b/tools-webrtc/ios/build_ios_libs.sh
@@ -113,7 +113,7 @@ SDK_FRAMEWORK_NAME="WebRTC.framework"
 
 BUILD_FLAVOR="release"
 BUILD_TYPE="framework"
-ENABLED_ARCHITECTURES=("arm" "arm64" "x64")
+ENABLED_ARCHITECTURES=("arm" "arm64" "x86" "x64")
 IOS_DEPLOYMENT_TARGET="8.0"
 LIBVPX_BUILD_VP9="false"
 USE_BITCODE="false"
@@ -179,6 +179,7 @@ elif [[ ${BUILD_TYPE} = "framework" ]]; then
   lipo ${ARM_LIB_PATH}/${DYLIB_PATH} \
        ${ARM64_LIB_PATH}/${DYLIB_PATH} \
        ${X64_LIB_PATH}/${DYLIB_PATH} \
+       ${X86_LIB_PATH}/${DYLIB_PATH} \
        -create -output ${SDK_OUTPUT_DIR}/${DYLIB_PATH}
 
   # Remove stray mobileprovision if it exists until chromium roll lands.
@@ -196,6 +197,7 @@ elif [[ ${BUILD_TYPE} = "framework" ]]; then
   lipo ${ARM_LIB_PATH}/${DSYM_PATH} \
       ${ARM64_LIB_PATH}/${DSYM_PATH} \
       ${X64_LIB_PATH}/${DSYM_PATH} \
+      ${X86_LIB_PATH}/${DYLIB_PATH} \
       -create -output ${SDK_OUTPUT_DIR}/${DSYM_PATH}
 
   # Modify the version number.
```

**Comment by jondwillis** [comment]
For context, I had to add i386 support when using WebRTC as a framework dependency of another Cocoapod. It does not validate without it. ¯\_(ツ)_/¯

**Comment by AlexKMDev** [comment]
@jondwillis thank you, it seems it's working now. I uploaded a new version.
