### ISSUE TITLE
Add multiple mediaConstraints

### ISSUE THREAD

**Issue by DustinBel** [Anakros/webrtc-ios-dynamic#17]
Is it possible to add more constrains? Because the current interface supports: 

init(mandatoryConstraints mandatory: [String : String]?, optionalConstraints optional: [String : String]?) 

So I can pass only 1 constraint. Is it possible to submit more mediaConstraints? Like OfferToReceiveAudio, OfferToReceiveVideo etc.

**Comment by AlexKMDev** [comment]
You can pass an dictionary of constraints, not just one.

```swift
RTCMediaConstraints(mandatoryConstraints: [
    "OfferToReceiveVideo": "true",
    "OfferToReceiveAudio": "false"
    ], optionalConstraints: [
     "DtlsSrtpKeyAgreement": "true",
     "googCpuLimitedResolution": "false"
    ]
)
```
