### ISSUE TITLE
dyld: Library not loaded. Reason: image not found

### ISSUE THREAD

**Issue by tanhoang181** [Anakros/webrtc-ios-dynamic#18]
Hello, I'm running the framework on simulators with Xcode 8.1 but it doesn't work at all and the error showed up every time.
Do I need to include some other libs or frameworks?

**Comment by AlexKMDev** [comment]
Are you using 32-bit simulator (iPhone 5 and below)? https://github.com/Anakros/WebRTC/issues/16#issuecomment-268421323

**Comment by tanhoang181** [comment]
No. I was using iPhone 6s simulator.

**Comment by AlexKMDev** [comment]
You don't need to include anything additional. Not sure what can be a problem, maybe old Xcode version. Can you include the full description of the error, i.e. path to the image that not found?

**Comment by tanhoang181** [comment]
dyld: Library not loaded: @rpath/WebRTC.framework/WebRTC
  Referenced from: /Users/hoangtan/Library/Developer/CoreSimulator/Devices/0EDE3787-FC46-4F47-8D1A-E6105E07F99E/data/Containers/Bundle/Application/977571ED-6862-42D3-95CD-B937E10A3EF2/webrtc.app/webrtc
  Reason: image not found

I got the message.

**Comment by alexeychirkov** [comment]
Add framework to target's Embeded binaries section
![](https://i.gyazo.com/074e0805b4befbef9489025569ecf503.png)

**Comment by danlniel** [comment]
I got same error, i have tried add framework to target's embeded still got same error.

**Comment by CoderXLL** [comment]
I have added framework to the target,but only run the framework on 8.1 simulators ,it doesn't work, the error is this:
dyld: Library not loaded: /System/Library/Frameworks/MetalKit.framework/MetalKit
  Referenced from: /private/var/mobile/Containers/Bundle/Application/8454DA05-F872-497A-A44A-F6261169E57B/EUCIMManager.app/Frameworks/WebRTC.framework/WebRTC
  Reason: image not found

**Comment by AlexKMDev** [comment]
Included a note about that in the README.
