### ISSUE TITLE
Install framework via cocoapod 

### ISSUE THREAD

**Issue by x3mall1986** [Anakros/webrtc-ios-dynamic#2]
if use 
`pod 'WebRTC'`

and than in terminal
`pod install`

result with error:

```
Analyzing dependencies
[!] There are only pre-release versions available satisfying the following requirements:

    'WebRTC', '>= 0'

You should explicitly specify the version in order to install a pre-release version
```

**Comment by AlexKMDev** [comment]
You can solve it by specifying the exact version starting from which all new versions of Pod will be installed: `pod "WebRTC", ">= 13641.0.06bfe1f"`

**Comment by AlexKMDev** [comment]
Works without specifying the version in the new release https://github.com/Anakros/WebRTC-iOS/releases/tag/1.0.13807
