### ISSUE TITLE
Wrong version naming?

### ISSUE THREAD

**Issue by bmaslakov** [Anakros/webrtc-ios-dynamic#20]
The latest release at this repository is [`56.10.15101`](https://github.com/Anakros/WebRTC/releases/tag/56.10.15101), but as far as I understand it should be `56.10.15644`.
Please see the [commit at googlesource](https://chromium.googlesource.com/external/webrtc/+/0010acb56e36c7abef3bb0761700e6a85b53dfbc), it clearly states that `Cr-Commit-Position` is `refs/heads/master@{#15644}`.

**Comment by bmaslakov** [comment]
Ok, I see you're using `Cr-Branched-From` for the revision number and I was referring to `Cr-Commit-Position`. I guess your approach is better.

**Comment by AlexKMDev** [comment]
I just follow stable branch naming in that case, not master one, i.e. `<branch number>.<update number>.<revision number>`. I thought that commit under revision `15644` just was cherry-picked from `master` to `56` branch, so the original revision still `15101`, but with 10 cherry-picked commits from `master`.

**Comment by bmaslakov** [comment]
Yep, you're right. I just got confused when I saw that revision number is not incremented for hotfixes.
