### ISSUE TITLE
Get the latest version of libwebrtc.a ios arm64

### ISSUE THREAD

**Issue by EbramTawfik** [Anakros/webrtc-ios-dynamic#22]
How can I get the latest version of `libwebrtc.a` ios arm64 ?

**Comment by AlexKMDev** [comment]
By compiling a static library from the upstream repository.

**Comment by EbramTawfik** [comment]
Do you mean the chromium native code repository ?
and how to do that because I compiled it I got " .framework " ?!

**Comment by AlexKMDev** [comment]
> Do you mean the chromium native code repository ?

Yes.
>  and how to do that because I compiled it I got " .framework " ?!

You should compile with `-b static_only` option and please ask questions not related to this binary build in the discussion group -- https://groups.google.com/forum/#!forum/discuss-webrtc
