### ISSUE TITLE
New build (release M58)

### ISSUE THREAD

**Issue by rmbrgn** [Anakros/webrtc-ios-dynamic#26]
Hello,

Any chance to have a freshly compiled version in the next days?
Or did I miss something about the release process?

Thanks a lot!

**Comment by chintan39** [comment]
There is a new release M58
https://groups.google.com/forum/#!topic/discuss-webrtc/13BE3fbHcLU

**Comment by AlexKMDev** [comment]
I'll upload a fresh build from M58 today.

**Comment by AlexKMDev** [comment]
Feel free to update via Cocoapods/Carthage. https://github.com/Anakros/WebRTC/releases/tag/58.17.16937
