### ISSUE TITLE
#import <WebRTC/RTCVideoCapturer.h> not found

### ISSUE THREAD

**Issue by shayanjalil** [Anakros/webrtc-ios-dynamic#27]
Hello,

I'm trying to integrate the framework in my project but I keep getting this error. I first built the framework from source and then also tried the pre-built framework from this repository.

In both cases I get this error. When I open the framework I cannot find the RTCVideoCapturer.h file under the headers folder. Is there something I'm missing here?

I'm integrating the framework in a swift project. I import the framework like this

`#import <WebRTC/WebRTC.h>`

in the bridging header.

Any help would be greatly appreciated

**Comment by AlexKMDev** [comment]
Hi.

I don't know exactly, but it probably happens because you have developed using old `libjingle_peerconnection`. `RTCVideoCapturer` was removed a long time ago in the upstream source code and we should use `RTCPeerConnectionFactory` to initialize the camera device now.

**Comment by shayanjalil** [comment]
Thanks for the help. I decided to use cocoapods. It's working fine now
