### ISSUE TITLE
[ASK] Build WebRTC Framework

### ISSUE THREAD

**Issue by danlniel** [Anakros/webrtc-ios-dynamic#28]
Sorry for being out of topic,
I need some help when i try build my own framework webrtc,
I got this error when trying to import on my project,
#import <WebRTC/WebRTC.h> ---> Could not build module 'WebRTC' 
Thank you.

**Comment by juancazalla** [comment]
Try adding 

`#import <WebRTC/RTCMTLVideoView.h>`

in WebRTC.h

**Comment by danlniel** [comment]
Thanks for your response, but still the problem appear
And i got this one, 
I change RTCVideoSource.h
```
#import <Foundation/Foundation.h>

#import <WebRTC/RTCMacros.h>
#import <WebRTC/RTCMediaSource.h>
#import <WebRTC/RTCVideoCapturer.h>

NS_ASSUME_NONNULL_BEGIN

RTC_EXPORT

@interface RTCVideoSource : RTCMediaSource <RTCVideoCapturerDelegate>

- (instancetype)init NS_UNAVAILABLE;

/**
 * Calling this function will cause frames to be scaled down to the
 * requested resolution. Also, frames will be cropped to match the
 * requested aspect ratio, and frames will be dropped to match the
 * requested fps. The requested aspect ratio is orientation agnostic and
 * will be adjusted to maintain the input orientation, so it doesn't
 * matter if e.g. 1280x720 or 720x1280 is requested.
 */
- (void)adaptOutputFormatToWidth:(int)width height:(int)height fps:(int)fps;

@end

NS_ASSUME_NONNULL_END
```
replace with this one

```
#import <Foundation/Foundation.h>

#import <WebRTC/RTCMacros.h>
#import <WebRTC/RTCMediaSource.h>

NS_ASSUME_NONNULL_BEGIN

RTC_EXPORT
@interface RTCVideoSource : RTCMediaSource

- (instancetype)init NS_UNAVAILABLE;

@end

NS_ASSUME_NONNULL_END
```
Did you know why this happen, my build is different with anarkos compiled? 
Even though i build with the same source.
I had pull and gclient sync with the latest version.
Thank you.

**Comment by danlniel** [comment]
SOLVED
It looks i need to fetch from release branch

> git fetch origin refs/branch-heads/$BRANCH
> git checkout FETCH_HEAD
> or
> git checkout -b branch_head_name branch-heads/$BRANCH
> gclient sync
