### ISSUE TITLE
RTCCameraVideoCapturer is missing

### ISSUE THREAD

**Issue by SemonCat** [Anakros/webrtc-ios-dynamic#29]
Hi, I need import RTCCameraVideoCapturer.h on my project,

but I can't find this file.

Can you add RTCCameraVideoCapturer.h to Headers?

**Comment by hansemannn** [comment]
It was an [open issue](https://bugs.chromium.org/p/webrtc/issues/detail?id=7488) that was closed last month. If someone can recompile the latest version and do a PR, that'd be awesome!

**Comment by AlexKMDev** [comment]
Included in the latest release.
