### ISSUE TITLE
14093 not working

### ISSUE THREAD

**Issue by wenxin3262** [Anakros/webrtc-ios-dynamic#3]
```
WebRTC/WebRTC.framework/Headers/RTCVideoSource.h:14:9: error: 'WebRTC/RTCMediaSource.h' file not found
```

Something wrong with RTCMediaSource.h got included in multiple locations, where this file does not exist in headers. I tired compile directly from webrtc repo, same error.

**Comment by AlexKMDev** [comment]
Should be upstream issue. Still exist in the latest revision (14110), so we need to wait until they fix it or use earlier version (from 54 release branch I guess).

**Comment by AlexKMDev** [comment]
fixed in 14141 https://github.com/Anakros/WebRTC-iOS/releases/tag/14141.0.0-master
