### ISSUE TITLE
dyld:Library not loaded:/System/Library/Frameworks/MetalKit.framework/MetalKit crashed on iOS8

### ISSUE THREAD

**Issue by CoderXLL** [Anakros/webrtc-ios-dynamic#30]
1.build is OK
2.but i found after version M58, run on iOS8 devive error:
dyld:Library not loaded:/System/Library/Frameworks/MetalKit.framework/MetalKit
Referenced from:/private/var/mobile/Containers/Bundle/Application/...
Reason:image not found
the version M58 is OK!
the newer always run error on iOS8 device

**Comment by AlexKMDev** [comment]
It's because RTCMTLVideoView was included for simulators, but Metal works only on real devices. Fixed in the current release.
