### ISSUE TITLE
universal release

### ISSUE THREAD

**Issue by antoniotuzzi** [Anakros/webrtc-ios-dynamic#5]
How difficult would be for you to obtain an universal framework ?
(with ios_deployment_target set to 8.0) ;)

**Comment by AlexKMDev** [comment]
What you mean by universal framework? For both iOS and macOS?

>  (with ios_deployment_target set to 8.0) ;) 

it's already done as you can see at `WebRTC.framework/Info.plist`

**Comment by antoniotuzzi** [comment]
universal: for armv7 arm64 x86_64 x86 (last 2 emulators)

**Comment by Anakros** [comment]
There is fat binary called `WebRTC`

**Comment by AlexKMDev** [comment]
There is fat binary called `WebRTC` included in framework. It's already built with following architectures: i386 x86_64 armv7 arm64

You can verify this by running `lipo -info WebRTC.framework/WebRTC`

``` fish
~/Downloads> lipo -info WebRTC.framework/WebRTC
Architectures in the fat file: WebRTC.framework/WebRTC are: i386 x86_64 armv7 arm64
```

So the framework is already built with these architectures.

**Comment by antoniotuzzi** [comment]
than there is something wrong: the FAT file should be at least 76MB

**Comment by AlexKMDev** [comment]
Why you think that? The framework was built in Release configuration and all debug information is located in dSYM file, so in total it will be ~75Mb as in similar frameworks, but with old code/revision.

It's a clean build from official repository using only provided script for building the framework and nothing else.
